### ISSUE TITLE
Enhancement: Add signed SLSA attestations to nightly docker builds

### ISSUE THREAD

**Issue by asraa** [tensorflow/build#125]
Hi! I'm reaching out on behalf of the [Open Source Security Foundation (openssf.org)](https://openssf.org/). We work on improving supply-chain security of critical open source projects. We believe we can help improve the tamper resistance of TF's nightly docker builds, with just a few lines of code. Starting with nightly docker builds is relatively low-risk, and allows some testing of the verification flow before moving to the more stable images.

[These](https://github.com/tensorflow/build/blob/428ab6533bdbcc9f8c1f2598825d8a2367368810/tf_sig_build_dockerfiles/README.md#tags) docker builds are built in this repository via GitHub Actions. Adding a  [provenance attestation](https://slsa.dev/provenance/v0.2) during the build process allows a cryptographically verifiable guarantee that the image was built in this repository. This provenance is a file with [metadata](https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/container#provenance-example)  that lets users know that the container images were built from your repository’s [workflow](https://github.com/tensorflow/build/blob/491856aa90413f54f6d442a2f04bc9ea8c96f337/.github/workflows/docker.yml) and not altered by anyone. 

The container provenance generator [workflow](https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/container) uploads the attestation in the registry using Sigstore's attestation [specification](https://github.com/sigstore/cosign/blob/92ce88e0fa077b50de9f9fe8772cdc893d58ca38/specs/ATTESTATION_SPEC.md). This is projected to go GA in the next few weeks (the API may be change in future releases of the generator), and we would love to use TF's nightly builds as an early adoption.

Generating these attestations is also a step toward adopting Supply-chain Levels for Software Artifacts ([SLSA](slsa.dev)). SLSA is a security framework to improve transparency and authenticity of the build / release process. It’s designed and used by a consortium of companies including Google, Intel, Chainguard, Citi, and Datadog, under the umbrella of the Open Source Security Foundation. By generating these attestations in the future for stable docker builds, your project will reach [SLSA Level 3](https://slsa.dev/spec/v0.1/levels#summary-of-levels) for provenance. You can even add a SLSA badge to your repository so users know that you take security seriously. 

If you're interested in reading more, check out this recent [blog post](https://slsa.dev/blog/2022/06/slsa-github-workflows), which describes how some of the recent supply-chain attacks would have been prevented using SLSA provenance.

Happy to answer any question you might have.

I'll follow up with a PR and link here to show the changes needed to add provenance to the docker workflow.

cc @ianlewis @mihaimaruseac @laurentsimon

**Comment by bhack** [comment]
Is this only related to the docker nightly images or also to the Tensorflow nightly wheels built with these images?

Cause we still don't publicly know on which specific nightly commits the nightly wheels are built. See:
https://github.com/tensorflow/build/issues/72

**Comment by mihaimaruseac** [comment]
They're not really related. The wheels need a lot more work to get attestations added.

**Comment by mihaimaruseac** [comment]
(closed by mistake on my fork)
