### ISSUE TITLE
Python 3.5 EOL

### ISSUE THREAD

**Issue by bhack** [tensorflow/build#14]
Python 3.5 is EOL starting from 13th Sept.
We have already discussed this in the Gitter channel this is just a reminder. 
Also many users could be confused by this warnings  e.g. when building the Raspberry wheel.

**Comment by mihaimaruseac** [comment]
We will drop support for Python3.5 this week, according to [announcement](https://groups.google.com/a/tensorflow.org/forum/#!topic/developers/Ip-UJMTXVx8)

**Comment by bhack** [comment]
I know please close this now or the next week as you want.

**Comment by mihaimaruseac** [comment]
Will close when the support is fully dropped. Just wanted to ping issue in case others are following.
