### ISSUE TITLE
Folder structure within the Project

### ISSUE THREAD

**Issue by sub-mod** [tensorflow/build#2]
## Expected Behavior
Probably a good idea to create a structure like named directories so that Contributors from  different vendors(IBM, RedHat, Intel etc) can contribute the build scripts in proper location. 

## Actual Behavior
Currently no directory structure exists.A bit confusing where to add files.

## Proposal

Create directories for different Platforms, common scripts , cpu/gpu, 

- common_scripts
- x86_64
- - cpu
- - - Dockerfile
- - - build_scripts
- - gpu
- - mkl
- ppc64le
- - cpu
- - gpu

@perfinion @ewilderj @wdirons

**Comment by wdirons** [comment]
I agree a folder convention would be nice. That above is fine, but I was thinking we may want to a  create a top level directory `ci_environments` short for continuous integration environments that each team can then have their own folder in that directory.  (The goal being for each team to show how they are doing continuous integration test for tensorflow.)

So the folders under that might be:

- ci_environments
  - common
  - redhat
  - mkl
  - ppc64le
     - cpu
       - Dockerfile
       - build_scripts
     - gpu
       - Dockerfile
       - build_scripts
  - romc


Then other build related work can go into folders separate from ci_environments

**Comment by perfinion** [comment]
Yeah a deeper / better directory structure is definitely good. For your suggested layout, do you mean under the `images/` dir?

There are several different things that are going on in the repo (or will be):

- Stuff to build containers. This is the Dockerfiles and all scripts they call (eg install_pip_packages.sh). These should be shared as much as possible and be as high in the tree as makes sense so things aren't duplicated.
- CI build scripts to build TF / other sig repos / associated projects.
- The configs for the actual CI systems. There is currently some amount of tekton config in here already, but we'll likely want jenkins stuff too. The configs should be as generic and configurable as possible so many different people can use them.

For the build containers, I like how subin suggested but maybe with build_scripts also one dir higher for the parts that are shared within all the targets within an arch. I don't think a redhat/ubuntu/mkl dir makes as much sense within the docker files, I think the dirs should be for what type of target they are. What do you think of something like `/images/amd64/cpu/Dockerfile.ubuntu1604` or `/images/amd64/rocm/Dockerfile.someversion` or `/images/ppc64le/gpu/Dockerfile.cuda10.2`.

Then we can have a /ci_environments/ibm/ or /ci_environtments/redhat/ where each organization can have their own customizations derived from some types of common scripts in /jenkins/ or /tekton/?

I'm not completely sure how generic all the different scripts will end up being so I suppose we just try and put as much in the common dirs as we can and split things out when there are conflicts?

**Comment by claynerobison** [comment]
Let's change mkl to the modern name: dnnl. See note at https://github.com/intel/mkl-dnn

**Comment by bhack** [comment]
@claynerobison Isn't the "more modern" name oneDnn? https://github.com/oneapi-src/oneDNN? :smile_cat:

**Comment by angerson** [comment]
This issue has been resolved by the folder structure we adopted not too long ago. Thank you for your contributions, everyone -- I'll close this issue and we can use another one if further discussion is needed.
