### ISSUE TITLE
Non existing archive 

### ISSUE THREAD

**Issue by vulkomilev** [tensorflow/build#45]
I am getting the following issue while building the tf in the docker image:
command : 

```
sudo docker exec tf bazel build --jobs 26   //tensorflow/tools/pip_package:build_pip_package
log:
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from /tf/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /tf/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library
INFO: Reading rc options for 'build' from /tf/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3/dist-packages --python_path=/usr/bin/python3
INFO: Reading rc options for 'build' from /tf/tensorflow/.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/fallback,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file /tf/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /tf/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /tf/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /tf/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/3e404ce1177fd189b28f0a84e75a43619dad01bd.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
```

I have tried to download the archive with wget but no luck with error 404(locally and on the docker container)

**Comment by angerson** [comment]
Thanks for the report. Can you give me some more information?

- What is the complete set of commands you used?
- Are you following [the instructions](https://github.com/tensorflow/build/tree/master/tf_sig_build_dockerfiles)? I don't see the suggested flags in your command.
- What happens after this if you wait for a few minutes? The warning by itself will not cause a breakage.

**Comment by vulkomilev** [comment]
What is the complete set of commands you used?
`2004  mkdir tf_docker
 2005  cd tf_docker/
 2006  ls
 2007  mkdir tensorflow
 2008  mkdir packages
 2009  mkdir bazelcache
 2010  docker pull tensorflow/build:latest-python3.9
 2011  sudo docker pull tensorflow/build:latest-python3.9
 2012  cd tensorflow/
 2013  cd ..
 2014* git pull
 2015  git clone https://github.com/tensorflow/tensorflow.git
 2016  tree
 2017  ls
 2018  ls ./tensorflow/
 2019  pwd
 2020  docker run --name tf -w /tf/tensorflow -it -d   -v "/home/<username>/open_source/tf_docker/packages:/tf/pkg"   -v "/home/<username>/open_source/tf_docker/tensorflow:/tf/tensorflow"   -v "/home/<username>/open_source/tf_docker/bazelcache:/tf/cache"   tensorflow/build:latest-python3.9   bash
 2021  sudo docker run --name tf -w /tf/tensorflow -it -d   -v "/home/<username>/open_source/tf_docker/packages:/tf/pkg"   -v "/home/<username>/open_source/tf_docker/tensorflow:/tf/tensorflow"   -v "/home/<username>/open_source/tf_docker/bazelcache:/tf/cache"   tensorflow/build:latest-python3.9   bash
 2022  docker exec tf python3 tensorflow/tools/ci_build/update_version.py --nightly
 2023  sudo docker exec tf python3 tensorflow/tools/ci_build/update_version.py --nightly
 2024  sudo docker exec sh ./configure
 2025  sudo docker exec bash ./configure
 2026  sudo docker exec  ./configure
 2027  sudo docker exec tf bash ./configure
 2029  sudo docker exec tf bash bazel build --jobs 26 --config=cuda  //tensorflow/tools/pip_package:build_pip_package
 2030  sudo docker exec tf bazel build --jobs 26   //tensorflow/tools/pip_package:build_pip_package
 2031  sudo docker exec tf ping 8.8.8.8
 2032  ping
 2033  sudo docker exec tf wget
 2034  sudo docker exec tf wget http://dir.bg
 2035  sudo docker exec tf wget ttps://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/3e404ce1177fd189b28f0a84e75a43619dad01bd.tar.gz
 2036  sudo docker exec tf wget https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/3e404ce1177fd189b28f0a84e75a43619dad01bd.tar.gz
`
Are you following the instructions?
Yes I don't know about any special flags  on step 6 where I stuck.
What happens after this if you wait for a few minutes? The warning by itself will not cause a breakage.
I didn't wait :) . I will try to wait and I will report the result

**Comment by angerson** [comment]
> Yes I don't know about any special flags on step 6 where I stuck.

Click on the down arrow next to the section you choose to see the instructions.
