### ISSUE TITLE
Docker exec ctrl+c suggestion

### ISSUE THREAD

**Issue by bhack** [tensorflow/build#49]
https://github.com/tensorflow/build/blob/42a990a6859d6acbb2e9667049d4105ce332965a/tf_sig_build_dockerfiles/README.md?plain=1#L67-L69

> - If you interrupt a `docker exec` command with `ctrl-c`, you will get your
  shell back but the command will continue to run. You cannot reattach to it.
  If you have any suggestions for handling this, let us know.

We could run a `tmux` or `byobu` session in the container so it could be easy to attach again to the session without having a detached process in case of `crtl+c`

**Comment by angerson** [comment]
We can revisit this once we're focusing contributor QoL for the containers. Right now I'm only concerned with CI, where this is not a problem.
