### ISSUE TITLE
Devel images without source

### ISSUE THREAD

**Issue by bhack** [tensorflow/build#6]
Can we push on dockerhub devel images without set `CHECKOUT_TF_SRC=1` buildargs?
Generally to develop on SIGs you don't need full Tensorflow soruce code checkout and we could recover 500+MB just bypassing the source code layer.
/cc @gunan

**Comment by gunan** [comment]
I think we include that, because we want to make sure to have the exact commit the devel image is built with. We had issues previously where the devel image was updated, and for a few days our users had quite a few issues to built TF.

**Comment by bhack** [comment]
I understand this and It could be also useful in other cases.
But as SIGs are advanced users I think we could have a source-less image on Dockerhub with almost the same layers (and so with a minimal push overhead).

**Comment by bhack** [comment]
As I think we will not have image unification quite soon on https://github.com/tensorflow/tensorflow/issues/38352 this devel image sourceless variants could be a valid alternative as a base for SIG docker images.

**Comment by bhack** [comment]
Also as currently at some point we stated to not pushing anymore versioned devel images like [this one](https://hub.docker.com/layers/tensorflow/tensorflow/1.12.0-devel-gpu-py3/images/sha256-d6c139d2fdbf1c0ea0084b2bcd28907ca672bb1f67124f1fd431ad010fd4e7c2?context=explore) I think that we could start again to publish that release format: 

E.g for 2.2.0 release: 

- `2.2.0-devel-src-gpu`
- `2.2.0-devel-gpu`
- `2.2.0-devel-src`
- `2.2.0-devel`

**Comment by gunan** [comment]
Unfortunately, any new tag we push brings nontrivial overheads for us.
So, we will need to weigh the options and get back on this.

**Comment by lgeiger** [comment]
@bhack Would using a shallow clone using `--depth=1` to add the TensorFlow source code work for you?
This would reduce the size of the source code from 807MB down to 288MB which is still quite large, but won't add additional maintenance overhead.

**Comment by bhack** [comment]
It Is better then nothing but I think that It will not have so much overhead if the layers are 99% the same between the two images (as we have already the boolean flag).

It think also that having the checkout could be confusing if you work with IDE e.g. like vscode and remote container extension or GitHub codespaces (they are quite the same technology) cause the repo checkout is going to be mounted as volume inside the container.

Generally also if you want to develop on a specific remote setup on  Kubernetes you will go to prepare the git clone  in the init container to have a better control of your fork/branches.
