### ISSUE TITLE
HTTP ERROR 404 Not Found

### ISSUE THREAD

**Issue by callmekofi** [tensorflow/build#63]
I get this error when I open the TensorFlow Builds ( Linux AMD ROCm GPU Stable : TF 2.x).  Also, I believe the img used in the readme didn't load. 

URI: | /job/tensorflow/job/release-rocmfork-r25-rocm-enhanced/job/rocm-4.2.0-python3x-whls/
-- | --

**Comment by perfinion** [comment]
Ping @deven-amd :)

**Comment by angerson** [comment]
These are now fixed
