### ISSUE TITLE
Custom release.sh is not executed

### ISSUE THREAD

**Issue by bhack** [tensorflow/build#7]
Seems that this script not executed anymore by the CI https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/release/ubuntu_16/custom_op/release.sh

**Comment by yifeif** [comment]
It is still used for releasing the custom op docker image (though it needs some update at head). Let's keep it.

**Comment by bhack** [comment]
Yes I didn't want to remove It.
It was related to check if It Is was still runned regularly cause the other script in the same ditectory (nightly.sh) is running.

**Comment by bhack** [comment]
@yifeif Can we rely on that script? Is it regularly included in the release pipeline now?

**Comment by bhack** [comment]
It seems that It is still not running in the internal pipeline also for 2.3.0:

https://hub.docker.com/r/tensorflow/tensorflow/tags?page=1&name=custom

**Comment by bhack** [comment]
Can we close this?
